# Generated by Django 4.1.5 on 2023-02-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("publish", models.BooleanField(default=False)),
                (
                    "jour",
                    models.CharField(
                        choices=[
                            ("Lundi", "Lundi"),
                            ("Mardi", "Mardi"),
                            ("Mercredi", "Mercredi"),
                            ("Jeudi", "Jeudi"),
                            ("Vendredi", "Vendredi"),
                            ("Samedi", "Samedi"),
                            ("Dimanche", "Dimanche"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
