# Generated by Django 4.1.1 on 2023-02-18 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_campagne_commande_intrant_prix_unite_uniteproduit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0006_enqueteur_acteur_utilisateur_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prix",
            name="code_enqueteur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.enqueteur",
            ),
        ),
        migrations.AddField(
            model_name="prix",
            name="code_marche",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="web.marche"
            ),
        ),
        migrations.AddField(
            model_name="prix",
            name="code_unite_produit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="app.uniteproduit",
            ),
        ),
        migrations.AddField(
            model_name="intrant",
            name="code_acteur_vendu",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="intrant",
            name="code_superficie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="web.filiere"
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="code_acteur_acheteur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer",
                to="web.acteur",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="code_acteur_vendeur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="seller",
                to="web.acteur",
            ),
        ),
    ]
