# Generated by Django 4.1.1 on 2023-03-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("publish", models.BooleanField(default=False)),
                ("code_commande", models.CharField(max_length=50)),
                ("date_commande", models.DateTimeField(auto_now=True)),
                ("quantite_demande", models.IntegerField()),
                ("quantite_livre", models.IntegerField()),
                ("date_livraison", models.DateTimeField()),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SortieStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("publish", models.BooleanField(default=False)),
                ("date_sortie", models.DateTimeField(auto_now=True)),
                ("quantite_sortie", models.IntegerField()),
                ("prix_vente", models.FloatField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("publish", models.BooleanField(default=False)),
                ("code_stock", models.CharField(max_length=50)),
                ("date_recolte", models.DateField(auto_now=True)),
                ("date_prelevement", models.DateField(auto_now=True)),
                ("quantite_stock", models.IntegerField()),
                ("information_production", models.TextField()),
                ("information_stockage", models.TextField()),
                ("photo", models.FileField(upload_to="img_stock")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
