# Generated by Django 4.1.1 on 2023-03-03 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("parametrage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0001_initial"),
        ("marche", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="marche",
            name="code_superviseur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="marche",
            name="code_type_marche",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="marche.typemarche",
            ),
        ),
        migrations.AddField(
            model_name="marche",
            name="jour_marche",
            field=models.ManyToManyField(to="parametrage.jour"),
        ),
        migrations.AddField(
            model_name="marche",
            name="locaclite",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parametrage.localite",
            ),
        ),
        migrations.AddField(
            model_name="magasin",
            name="code_acteur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.acteur",
            ),
        ),
        migrations.AddField(
            model_name="magasin",
            name="localite_magasin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="parametrage.localite",
            ),
        ),
    ]
