# Generated by Django 4.1.5 on 2023-02-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_typeacteur_acteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acteur',
            name='type_acteur',
        ),
        migrations.AddField(
            model_name='acteur',
            name='type_acteur',
            field=models.ManyToManyField(to='users.typeacteur'),
        ),
    ]
