# Generated by Django 4.1.5 on 2023-02-07 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('code_filiere', models.CharField(max_length=50)),
                ('nom_filiere', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeFilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('code_type_filiere', models.CharField(max_length=50)),
                ('nom_type_filiere', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('nom_produit', models.CharField(max_length=250)),
                ('code_produit', models.CharField(max_length=50)),
                ('forme_produit', models.CharField(max_length=50)),
                ('maillon_produit', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='img_produit')),
                ('description', models.TextField()),
                ('code_filier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.filiere')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='filiere',
            name='code_type_filiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.typefilier'),
        ),
    ]
