# Generated by Django 4.1.5 on 2023-02-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marche",
            name="jour_marche",
        ),
        migrations.AddField(
            model_name="marche",
            name="jour_marche",
            field=models.ManyToManyField(to="app.jour"),
        ),
    ]
