# Generated by Django 4.1.5 on 2023-02-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filiere',
            name='code_type_filiere',
        ),
    ]
