# Generated by Django 4.1.5 on 2023-02-07 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_filiere_code_type_filiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeMarche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('code_type_marche', models.CharField(max_length=50)),
                ('nom_type_marche', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('code_marche', models.CharField(max_length=50)),
                ('locaclite', models.CharField(max_length=250)),
                ('jour_marche', models.CharField(max_length=50)),
                ('code_superviseur', models.CharField(max_length=50)),
                ('coordonnee_geo', models.CharField(max_length=250)),
                ('superficie', models.CharField(max_length=250)),
                ('caracteristique', models.CharField(max_length=250)),
                ('photo', models.FileField(upload_to='img_marche')),
                ('code_type_marche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.typemarche')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
