# Generated by Django 4.1.5 on 2023-02-09 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_remove_marche_jour_marche_marche_jour_marche"),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("publish", models.BooleanField(default=False)),
                ("nom_region", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="magasin",
            name="code_acteur",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="web.acteur"
            ),
        ),
        migrations.CreateModel(
            name="Localite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("publish", models.BooleanField(default=False)),
                ("nom_localite", models.CharField(max_length=50)),
                (
                    "region",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.region",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="magasin",
            name="localite_magasin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.localite",
            ),
        ),
        migrations.AlterField(
            model_name="marche",
            name="locaclite",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.localite",
            ),
        ),
    ]
