# Generated by Django 4.1.5 on 2023-02-10 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_region_alter_magasin_code_acteur_localite_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("publish", models.BooleanField(default=False)),
                ("nom_forme", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Maillon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("publish", models.BooleanField(default=False)),
                ("nom_maillon", models.CharField(max_length=50)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="produit",
            name="code_filier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.filiere",
            ),
        ),
        migrations.RemoveField(
            model_name="produit",
            name="maillon_produit",
        ),
        migrations.AlterField(
            model_name="produit",
            name="forme_produit",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="web.forme"
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="maillon_produit",
            field=models.ManyToManyField(to="web.maillon"),
        ),
    ]
