# Generated by Django 4.1.5 on 2023-02-07 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0003_typemarche_marche'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeActeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('code_type_acteur', models.CharField(max_length=150)),
                ('libele', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Acteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('code_acteur', models.CharField(max_length=50)),
                ('coordonnee', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='acteur_img')),
                ('description', models.TextField()),
                ('type_acteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.typeacteur')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
