# Generated by Django 4.1.5 on 2023-02-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_typeacteur_acteur'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acteur',
        ),
        migrations.DeleteModel(
            name='TypeActeur',
        ),
    ]
