# Generated by Django 4.1.1 on 2023-02-18 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_campagne_commande_intrant_prix_unite_uniteproduit_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("web", "0005_remove_acteur_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enqueteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("publish", models.BooleanField(default=False)),
                ("code_enqueteur", models.CharField(max_length=50)),
                ("nom_enqueteur", models.CharField(max_length=250)),
                ("localite_enqueteur", models.CharField(max_length=250)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Homme"), ("F", "Femme")], max_length=50
                    ),
                ),
                ("photo", models.FileField(upload_to="img_enqueteur")),
                (
                    "code_acteur",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="acteur",
            name="utilisateur",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_acteur",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="filiere",
            name="code_type_filiere",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.typefilier",
            ),
        ),
        migrations.AddField(
            model_name="marche",
            name="nom_marche",
            field=models.CharField(default="marché mamiAdjoua", max_length=250),
        ),
        migrations.AddField(
            model_name="typeacteur",
            name="nom_type_acteur",
            field=models.CharField(default="agriculteur", max_length=250),
        ),
        migrations.AlterField(
            model_name="marche",
            name="code_type_marche",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="web.typemarche",
            ),
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("publish", models.BooleanField(default=False)),
                ("code_stock", models.CharField(max_length=50)),
                ("date_recolte", models.DateField(auto_now=True)),
                ("date_prelevement", models.DateField(auto_now=True)),
                ("quantite_stock", models.IntegerField()),
                ("information_production", models.TextField()),
                ("information_stockage", models.TextField()),
                ("photo", models.FileField(upload_to="img_stock")),
                (
                    "code_acteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.acteur",
                    ),
                ),
                (
                    "code_enqueteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.enqueteur",
                    ),
                ),
                (
                    "code_magasin",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.magasin",
                    ),
                ),
                (
                    "code_produit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.produit",
                    ),
                ),
                (
                    "code_unite_produit",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="app.uniteproduit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SortieStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_add", models.DateTimeField(auto_now_add=True)),
                ("date_update", models.DateTimeField(auto_now=True)),
                ("publish", models.BooleanField(default=False)),
                ("date_sortie", models.DateTimeField(auto_now=True)),
                ("quantite_sortie", models.IntegerField()),
                ("prix_vente", models.FloatField()),
                (
                    "code_acteur_destinateur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.acteur",
                    ),
                ),
                (
                    "code_enqueteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="web.enqueteur",
                    ),
                ),
                (
                    "code_stock",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="web.stock"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
