# Generated by Django 4.1.5 on 2023-02-07 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_typeacteur_acteur'),
        ('web', '0005_delete_acteur_delete_typeacteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('publish', models.BooleanField(default=False)),
                ('code_magasin', models.CharField(max_length=50)),
                ('localite_magasin', models.CharField(max_length=250)),
                ('coordonnee_geo', models.CharField(max_length=250)),
                ('volume', models.IntegerField()),
                ('caracteristique', models.TextField()),
                ('photo', models.FileField(upload_to='img_magasin')),
                ('code_acteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.acteur')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
