# Generated by Django 4.1.1 on 2023-02-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0007_alter_acteur_utilisateur"),
    ]

    operations = [
        migrations.AddField(
            model_name="acteur",
            name="categorie",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="acteur",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="acteur",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="acteur",
            name="nom",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name="acteur",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="acteur",
            name="coordonnee",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
